# multi-node-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.30.4
  - role: worker
    image: kindest/node:v1.30.4
  - role: worker
    image: kindest/node:v1.30.4
  - role: worker
    image: kindest/node:v1.30.4


# kind create cluster --config <conf-name>.yaml --name  chat-prod

---
# multi nodes path mount 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.30.4
  - role: worker
    image: kindest/node:v1.30.4
    extraMounts:
      - containerPath: /mnt/data
        hostPath: /mnt/data
        propagation: HostToContainer
  - role: worker
    image: kindest/node:v1.30.4
    extraMounts:
      - containerPath: /mnt/data
        hostPath: /mnt/data
        propagation: HostToContainer
  - role: worker
    image: kindest/node:v1.30.4
    extraMounts:
      - containerPath: /mnt/data
        hostPath: /mnt/data
        propagation: HostToContainer


# kind create cluster --config kind-cluster-1M-3W-v1.30.yaml --name  chat-prod