version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
    - "3306:3306"
    volumes:
    - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
