apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=    #BASE64_ENCODED_PASSWORD


# Replace BASE64_ENCODED_PASSWORD with the Base64-encoded value of your MySQL root password. 
# You can use the echo -n 'your-password' | base64 command to generate the encoded password.