# Extreme Bulk Logging Pod in default ns (payment-app)
apiVersion: v1
kind: Pod
metadata:
  name: extreme-bulk-payment-logger
spec:
  containers:
  - name: extreme-bulk-payment-log-generator
    image: busybox
    resources:
      limits:
        cpu: 1000m    # Increased CPU limit for heavy log generation
        memory: 1Gi    # Increased memory to handle larger logs
      requests:
        cpu: 1000m    # Increased CPU request for constant log generation
        memory: 1Gi    # Increased memory request
    args:
      - /bin/sh
      - -c
      - |
        while true; do
          timestamp=$(date '+%Y-%m-%d %H:%M:%S')
          user="user$((RANDOM % 100 + 1))"   # Increase random user pool for more variance
          order_id="order$((RANDOM % 1000 + 1))"
          transaction_id="txn$((RANDOM % 10000 + 1))"
          action_num=$((RANDOM % 8))

          # Generate 10 log entries at once to increase volume
          for i in {1..10}; do
            case $action_num in
              0) echo "$timestamp | INFO | User: $user | Action: User logged in";;
              1) echo "$timestamp | INFO | User: $user | Action: Payment initiated | Order ID: $order_id | Transaction ID: $transaction_id";;
              2) echo "$timestamp | SUCCESS | User: $user | Action: Payment completed | Order ID: $order_id | Transaction ID: $transaction_id";;
              3) echo "$timestamp | WARNING | User: $user | Action: Payment pending | Order ID: $order_id";;
              4) echo "$timestamp | ERROR | User: $user | Action: Payment failed | Order ID: $order_id | Reason: Insufficient funds";;
              5) echo "$timestamp | INFO | User: $user | Action: Logout";;
              6) echo "$timestamp | INFO | User: $user | Action: Order confirmed | Order ID: $order_id";;
              7) echo "$timestamp | INFO | User: $user | Action: Cart cleared";;
            esac
          done

          # Sleep for a very short time to ensure logs are generated at a high frequency
          sleep 0.01  # Sleep for 10ms to generate logs extremely fast
        done
