apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-intensive-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memory-intensive-app
  template:
    metadata:
      labels:
        app: memory-intensive-app
    spec:
      containers:
      - name: memory-app
        image: ubuntu:latest
        command:
        - "bash"
        - "-c"
        - |
          apt-get update && apt-get install -y stress && \
          stress --vm 1 --vm-bytes 2G --vm-hang 0
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "2Gi"
